Component table
JSL-Future/jsl-2.0 pull request #4
Opened 2020-10-09 20:25 UTC by tthiagoramalhot

2020-10-09 21:18 UTC, alexandrejuk requested changes

2020-10-09 21:18 UTC, alexandrejuk commented on src/Components/Table/index.js
> +          </tr>
Esse cara tem que ser um map igual do select option

2020-10-09 21:18 UTC, alexandrejuk commented on src/Components/Table/style.module.css
> +td{
tem que colocar espaço antes da chave

2020-10-09 21:18 UTC, alexandrejuk commented on src/Components/Table/style.module.css
> +tr{
tem que colocar espaço antes da chave

2020-10-13 15:23 UTC, alexandrejuk requested changes

2020-10-13 15:23 UTC, alexandrejuk commented on src/Components/Table/index.js
> +          }
tem quanto de espaço na indentação deveria está com 2

2020-10-13 15:28 UTC, tthiagoramalhot commented on src/Components/Table/index.js
> +          }
esta com 2 de espaço

2020-10-14 11:37 UTC, alexandrejuk approved these changes

2020-10-14 11:38 UTC, merged