Container create entry
JSL-Future/jsl-2.0 pull request #9
Opened 2020-10-15 14:18 UTC by thiagordsouza

2020-10-16 18:57 UTC, alexandrejuk requested changes

2020-10-16 18:57 UTC, alexandrejuk commented on src/Containers/Create/index.js
> +          onChange=""
faltou o onchange

2020-10-16 18:57 UTC, alexandrejuk commented on src/Containers/Create/index.js
> +          onChange=""
faltou o onchance

2020-10-21 11:56 UTC, alexandrejuk requested changes

2020-10-21 11:56 UTC, alexandrejuk commented on src/Containers/Create/index.js
> +          onChange={props.driverOnChage}
é um onchange para um component só todos os components até para o selectoptions

2020-10-22 11:58 UTC, thiagordsouza commented on src/Containers/Create/index.js
> +          onChange={props.driverOnChage}
Não entendi o que é para ser feito

2020-10-28 13:00 UTC, merged